import { StyleSheet, Dimensions, Platform } from 'react-native';

export const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');


export const styles = StyleSheet.create({
  // LUXURY DARK THEME - Brass Filigree & Black Leather
  container: {
    flex: 1,
    backgroundColor: '#0A0A0A',
  },
  // Image Quality Warning Banner Styles
  qualityWarningBanner: {
    backgroundColor: '#2D1F00',
    borderWidth: 1,
    borderColor: '#C9A227',
    borderRadius: 12,
    marginHorizontal: 16,
    marginTop: 12,
    padding: 14,
  },
  qualityWarningHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  qualityWarningIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  qualityWarningTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#C9A227',
    flex: 1,
  },
  qualityWarningClose: {
    padding: 4,
  },
  qualityWarningCloseText: {
    color: '#8B7355',
    fontSize: 16,
    fontWeight: '600',
  },
  qualityWarningText: {
    color: '#E5C76B',
    fontSize: 13,
    marginBottom: 4,
    marginLeft: 26,
  },
  qualitySuggestionsContainer: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#3D2D10',
  },
  qualitySuggestionsTitle: {
    color: '#C9A227',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 4,
  },
  qualitySuggestionText: {
    color: '#9CA3AF',
    fontSize: 12,
    marginLeft: 20,
    marginBottom: 2,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 2,
    borderBottomColor: '#C9A227',
    backgroundColor: '#0D0D0D',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  headerIconButton: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(26,26,26,0.8)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#444',
  },
  headerIconText: {
    fontSize: 18,
  },
  headerLogo: {
    width: 42,
    height: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#C9A227',
  },
  headerTitleContainer: {
    flexDirection: 'column',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#C9A227',
    letterSpacing: 2,
  },
  headerSubtitle: {
    fontSize: 10,
    fontWeight: '600',
    color: '#8B7355',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  helpButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#C9A227',
    justifyContent: 'center',
    alignItems: 'center',
  },
  helpButtonText: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '700',
  },
  galleryButton: {
    padding: 5,
    borderWidth: 1,
    borderColor: '#C9A227',
    borderRadius: 6,
  },
  iconText: {
    fontSize: 16,
  },
  placeholderIcon: {
    fontSize: 48,
  },
  holdHintIcon: {
    fontSize: 12,
    marginRight: 4,
  },
  compareIconText: {
    fontSize: 16,
    marginRight: 4,
  },
  exportIconText: {
    fontSize: 18,
  },
  closeIcon: {
    fontSize: 24,
    color: '#C9A227',
    fontWeight: '300',
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: 12,
  },
  deleteIcon: {
    fontSize: 16,
  },
  invertIcon: {
    fontSize: 16,
    marginRight: 4,
  },
  modeIcon: {
    fontSize: 16,
    marginRight: 4,
  },
  generateIcon: {
    fontSize: 20,
    marginRight: 6,
  },
  saveIcon: {
    fontSize: 18,
    marginRight: 6,
  },
  sliderIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  modalCloseIcon: {
    fontSize: 28,
    color: '#C9A227',
    fontWeight: '300',
    backgroundColor: 'rgba(0,0,0,0.5)',
    width: 36,
    height: 36,
    borderRadius: 18,
    textAlign: 'center',
    lineHeight: 36,
  },
  zoomButtonText: {
    fontSize: 24,
    color: '#fff',
    fontWeight: '300',
  },
  previewCompareIcon: {
    fontSize: 18,
    marginRight: 6,
  },
  previewActionIcon: {
    fontSize: 22,
    marginBottom: 4,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
  },
  imageArea: {
    flex: 1,
    overflow: 'hidden',
  },
  bottomBar: {
    backgroundColor: '#0D0D0D',
    borderTopWidth: 1,
    borderTopColor: '#2A2A2A',
    paddingTop: 4,
    paddingBottom: 8,
  },
  previewSection: {
    flex: 1,
    marginHorizontal: 12,
  },
  placeholderContainer: {
    flex: 1,
    minHeight: 350,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#2D2D2D',
    borderStyle: 'dashed',
  },
  placeholderText: {
    color: '#6B7280',
    fontSize: 16,
    marginTop: 12,
  },
  imagesContainer: {
    flex: 1,
  },
  imageWrapper: {
    flex: 1,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 8,
    overflow: 'hidden',
  },
  imageLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  imageLabel: {
    color: '#9CA3AF',
    fontSize: 14,
    fontWeight: '600',
  },
  holdHintContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(201, 162, 39, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  holdHintText: {
    color: '#C9A227',
    fontSize: 11,
    fontWeight: '500',
  },
  stencilLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  updatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(201, 162, 39, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  updatingText: {
    color: '#C9A227',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 6,
  },
  stencilImageContainer: {
    position: 'relative',
  },
  imageUpdating: {
    opacity: 0.6,
  },
  previewImage: {
    width: '100%',
    flex: 1,
    alignSelf: 'stretch',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
  },
  sourceButtons: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 12,
    paddingTop: 6,
    paddingBottom: 2,
  },
  sourceButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A1510',
    paddingVertical: 10,
    borderRadius: 10,
    gap: 6,
    borderWidth: 1,
    borderColor: '#3D3428',
  },
  sourceButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  editSourceButton: {
    backgroundColor: '#2A2018',
    borderColor: '#C9A227',
  },
  buttonIcon: {
    fontSize: 16,
  },
  toolIcon: {
    fontSize: 18,
  },
  resetButton: {
    backgroundColor: '#1A1510',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3D3428',
  },
  settingsSection: {
    marginTop: 24,
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    padding: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#C9A227',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  liveUpdateHint: {
    fontSize: 11,
    color: '#C9A227',
    fontWeight: '600',
  },
  sliderContainer: {
    marginBottom: 20,
  },
  sliderHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  sliderLabel: {
    color: '#A89060',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 8,
    flex: 1,
  },
  sliderValueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  miniLoader: {
    marginRight: 6,
  },
  sliderValue: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '700',
  },
  slider: {
    width: '100%',
    height: 40,
  },
  invertToggle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  invertToggleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  invertToggleLabel: {
    color: '#A89060',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 8,
  },
  toggleSwitch: {
    width: 50,
    height: 28,
    backgroundColor: '#1A1510',
    borderRadius: 14,
    padding: 3,
    borderWidth: 1,
    borderColor: '#3D3428',
  },
  toggleSwitchActive: {
    backgroundColor: '#C9A227',
  },
  toggleKnob: {
    width: 22,
    height: 22,
    backgroundColor: '#fff',
    borderRadius: 11,
  },
  toggleKnobActive: {
    marginLeft: 'auto',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  actionButtonsContainer: {
    marginTop: 16,
  },
  generateButtonRow: {
    flexDirection: 'row',
    gap: 10,
  },
  saveButtonsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  processButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A1510',
    paddingVertical: 12,
    borderRadius: 10,
    gap: 6,
    borderWidth: 2,
    borderColor: '#C9A227',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.98 }],
  },
  processButtonText: {
    color: '#C9A227',
    fontSize: 15,
    fontWeight: '700',
  },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A1510',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#C9A227',
    gap: 8,
  },
  saveToDeviceButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2D5A3D',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#4A9B5C',
    gap: 8,
  },
  saveToDeviceButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  saveButtonText: {
    color: '#C9A227',
    fontSize: 15,
    fontWeight: '700',
  },
  bottomSpacer: {
    height: 40,
  },
  // Gallery Modal Styles - Luxury Theme
  galleryContainer: {
    flex: 1,
    backgroundColor: '#0A0A0A',
  },
  galleryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#C9A227',
    backgroundColor: '#0D0D0D',
  },
  galleryTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#C9A227',
    letterSpacing: 1,
  },
  closeButton: {
    padding: 4,
  },
  galleryScroll: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  galleryItemContainer: {
    backgroundColor: '#0D0D0D',
    borderRadius: 12,
    marginBottom: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#3D3428',
  },
  galleryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  galleryImage: {
    width: 70,
    height: 70,
    borderRadius: 8,
    backgroundColor: '#1A1510',
    borderWidth: 1,
    borderColor: '#C9A227',
  },
  galleryItemInfo: {
    flex: 1,
    marginLeft: 12,
  },
  galleryItemName: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '700',
  },
  galleryItemDate: {
    color: '#6B5D48',
    fontSize: 11,
    marginTop: 4,
  },
  deleteButton: {
    padding: 10,
    backgroundColor: '#5C1F1F',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B3A3A',
  },
  // Version Selector Styles - Luxury Theme
  versionSelectorSection: {
    backgroundColor: '#0D0D0D',
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: '#C9A227',
  },
  versionSelectorTitle: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  versionSelectorSubtitle: {
    color: '#8B7355',
    fontSize: 11,
    marginBottom: 12,
  },
  versionButtonsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  versionButton: {
    flex: 1,
    backgroundColor: '#1A1510',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 6,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3D3428',
  },
  versionButtonSelected: {
    borderColor: '#C9A227',
    backgroundColor: '#1F1A12',
    borderWidth: 2,
  },
  versionButtonDisabled: {
    opacity: 0.4,
  },
  versionButtonEmoji: {
    fontSize: 18,
    marginBottom: 4,
  },
  versionButtonText: {
    color: '#A89060',
    fontSize: 12,
    fontWeight: '700',
  },
  versionButtonTextSelected: {
    color: '#C9A227',
  },
  versionButtonDesc: {
    color: '#6B5D48',
    fontSize: 9,
    marginTop: 2,
    textAlign: 'center',
  },
  // Generation Progress Styles
  generationProgressSection: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 20,
    marginTop: 16,
    alignItems: 'center',
  },
  generationProgressTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 16,
  },
  progressDotsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  progressDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#1A1510',
    borderWidth: 1,
    borderColor: '#3D3428',
  },
  progressDotComplete: {
    backgroundColor: '#C9A227',
  },
  generationProgressLabel: {
    color: '#9CA3AF',
    fontSize: 14,
  },
  emptyGallery: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    color: '#6B7280',
    fontSize: 16,
    marginTop: 12,
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
  },
  // Save Modal Styles
  saveModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  saveModalContent: {
    width: '100%',
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    padding: 24,
  },
  saveModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 16,
    textAlign: 'center',
  },
  saveModalInput: {
    backgroundColor: '#0F0F0F',
    borderRadius: 12,
    padding: 16,
    color: '#fff',
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#2D2D2D',
  },
  saveModalButtons: {
    flexDirection: 'row',
    marginTop: 20,
    gap: 12,
  },
  saveModalCancel: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#1A1510',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3D3428',
  },
  saveModalCancelText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  saveModalSave: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#C9A227',
    alignItems: 'center',
  },
  saveModalSaveText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  // NEW COMPACT UI STYLES
  compactToolsContainer: {
    flexDirection: 'row',
    marginTop: 12,
    gap: 10,
    alignItems: 'center',
  },
  compactCropButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A1A1A',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#333',
    gap: 6,
  },
  compactToolIcon: {
    fontSize: 16,
  },
  compactToolText: {
    color: '#9CA3AF',
    fontSize: 13,
    fontWeight: '600',
  },
  compactGenerateButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#C9A227',
    paddingVertical: 14,
    borderRadius: 25,
    gap: 8,
  },
  compactGenerateIcon: {
    fontSize: 18,
  },
  compactGenerateText: {
    color: '#0A0A0A',
    fontSize: 15,
    fontWeight: '700',
  },
  // Auto-Enhance Toggle Styles
  autoEnhanceContainer: {
    marginTop: 10,
    marginHorizontal: 0,
  },
  autoEnhanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1A1A1A',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
  },
  autoEnhanceLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  autoEnhanceIcon: {
    fontSize: 18,
    marginRight: 10,
  },
  autoEnhanceTextContainer: {
    flex: 1,
  },
  autoEnhanceLabel: {
    color: '#E5E5E5',
    fontSize: 14,
    fontWeight: '600',
  },
  autoEnhanceDescription: {
    color: '#888',
    fontSize: 11,
    marginTop: 2,
  },
  autoEnhanceToggle: {
    width: 46,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#333',
    padding: 2,
    justifyContent: 'center',
  },
  autoEnhanceToggleOn: {
    backgroundColor: '#C9A227',
  },
  autoEnhanceToggleKnob: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#888',
  },
  autoEnhanceToggleKnobOn: {
    backgroundColor: '#FFF',
    alignSelf: 'flex-end',
  },
  methodToggle: {
    flexDirection: 'row',
    backgroundColor: '#333',
    borderRadius: 8,
    padding: 2,
  },
  methodToggleText: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: '600',
    color: '#888',
    borderRadius: 6,
  },
  methodToggleActive: {
    color: '#0A0A0A',
    backgroundColor: '#C9A227',
  },
  cvInfoRow: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#222',
  },
  cvInfoText: {
    color: '#888',
    fontSize: 11,
    textAlign: 'center',
  },
  sliderRow: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#222',
  },
  sliderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sliderLabel: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
  },
  sliderValue: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '700',
    minWidth: 30,
    textAlign: 'right',
  },
  sliderTrack: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#333',
    borderRadius: 10,
    padding: 8,
  },
  sliderDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#555',
    borderWidth: 2,
    borderColor: '#444',
  },
  sliderDotActive: {
    backgroundColor: '#C9A227',
    borderColor: '#E0B82E',
  },
  sliderLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  sliderMinMax: {
    color: '#888',
    fontSize: 11,
  },
  lineWeightSection: {
    marginTop: 12,
    marginHorizontal: 12,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#333',
  },
  lineWeightHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  lineWeightLabel: {
    color: '#C9A227',
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  lineWeightValue: {
    color: '#888',
    fontSize: 12,
  },
  lineWeightSlider: {
    width: '100%',
    height: 40,
  },
  lineWeightLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: -4,
  },
  lineWeightEndLabel: {
    color: '#666',
    fontSize: 10,
  },
  compactVersionSection: {
    marginTop: 10,
  },
  // Custom Button Style Selection - Dark Charcoal with Brass Labels
  stencilStyleSection: {
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  styleLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 4,
  },
  styleBrassLabel: {
    color: '#C9A227',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    fontFamily: Platform.OS === 'ios' ? 'Helvetica Neue' : 'sans-serif',
    flex: 1,
    textAlign: 'center',
  },
  styleButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'flex-start',
    paddingHorizontal: 20,
    width: '100%',
  },
  styleButtonColumn: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  styleHistoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    gap: 8,
    backgroundColor: '#1a1a1a',
    borderRadius: 6,
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderColor: '#333',
  },
  styleHistoryArrow: {
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  styleHistoryArrowText: {
    color: '#C9A227',
    fontSize: 12,
    fontWeight: '700',
  },
  styleHistoryCounter: {
    color: '#999',
    fontSize: 11,
    fontWeight: '600',
    minWidth: 24,
    textAlign: 'center',
  },
  regenHintText: {
    color: '#C9A227',
    fontSize: 11,
    textAlign: 'center',
    paddingHorizontal: 16,
    paddingTop: 5,
    paddingBottom: 2,
    fontStyle: 'italic',
    opacity: 0.85,
  },
  styleButtonWrapper: {
    width: Math.min(110, (SCREEN_WIDTH - 60) / 3),
    height: Math.min(138, (SCREEN_WIDTH - 60) / 3 * 1.25),
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#8B7320',
    borderTopColor: '#A68B26',
    borderLeftColor: '#A68B26',
    borderBottomColor: '#5C4D16',
    borderRightColor: '#5C4D16',
  },
  styleButtonSelected: {
    // Brighter brass when selected
    borderWidth: 3,
    borderColor: '#C9A227',
    borderTopColor: '#E0B82E',
    borderLeftColor: '#E0B82E',
    borderBottomColor: '#9A7B1E',
    borderRightColor: '#9A7B1E',
  },
  styleButtonDisabled: {
    opacity: 0.5,
  },
  styleButtonImage: {
    width: '100%',
    height: '100%',
    backgroundColor: '#0A0A0A',
  },
  styleRegenButton: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: 'rgba(26,26,26,0.9)',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#333',
  },
  styleGeneratingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cropTopButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(26,26,26,0.9)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#444',
  },
  cropTopIcon: {
    fontSize: 14,
    marginRight: 5,
  },
  cropTopText: {
    color: '#C9A227',
    fontSize: 12,
    fontWeight: '600',
  },
  compactVersionRow: {
    flexDirection: 'row',
    gap: 8,
  },
  compactVersionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A1A1A',
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#333',
    gap: 4,
  },
  compactVersionSelected: {
    backgroundColor: '#C9A227',
    borderColor: '#C9A227',
  },
  compactVersionDisabled: {
    opacity: 0.4,
  },
  compactVersionEmoji: {
    fontSize: 14,
  },
  compactVersionText: {
    color: '#9CA3AF',
    fontSize: 12,
    fontWeight: '600',
  },
  compactVersionTextSelected: {
    color: '#0A0A0A',
  },
  regenButton: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#333',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#C9A227',
  },
  regenButtonText: {
    fontSize: 10,
  },
  compactProgressSection: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  compactProgressText: {
    color: '#C9A227',
    fontSize: 13,
    fontWeight: '500',
  },
  compactProgressDots: {
    flexDirection: 'row',
    gap: 6,
  },
  compactDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#333',
  },
  compactDotComplete: {
    backgroundColor: '#C9A227',
  },
  // Edit Tools Styles (legacy - keeping for reference)
  editToolsSection: {
    marginTop: 16,
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    padding: 16,
  },
  editToolsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#9CA3AF',
    marginBottom: 12,
  },
  editToolsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 8,
    marginBottom: 16,
  },
  editToolButton: {
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#1A1A1A',
    minWidth: 65,
  },
  editToolButtonActive: {
    backgroundColor: '#C9A227',
  },
  editToolIcon: {
    fontSize: 20,
    marginBottom: 4,
  },
  editToolText: {
    color: '#9CA3AF',
    fontSize: 11,
    fontWeight: '500',
  },
  editToolTextActive: {
    color: '#0A0A0A',
    fontWeight: '700',
  },
  editToolButtonText: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '600',
  },
  // Crop Modal Styles
  cropModalContainer: {
    flex: 1,
    backgroundColor: '#0F0F0F',
  },
  cropModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#1F1F1F',
  },
  cropModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
  },
  cropHeaderButton: {
    padding: 8,
  },
  cropApplyText: {
    color: '#10B981',
    fontSize: 16,
    fontWeight: '600',
  },
  cropCancelText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '400',
  },
  // Visual Crop Styles
  cropAreaContainer: {
    flex: 1,
    margin: 20,
    position: 'relative',
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    overflow: 'hidden',
  },
  cropFullImage: {
    width: '100%',
    height: '100%',
  },
  cropDarkOverlay: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  cropBoxBorder: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#C9A227',
    backgroundColor: 'transparent',
  },
  cropGridLineH: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  cropGridLineV: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  cropCornerHandle: {
    position: 'absolute',
    width: 24,
    height: 24,
    backgroundColor: '#C9A227',
    borderRadius: 12,
    borderWidth: 3,
    borderColor: '#fff',
  },
  cropCornerTL: {},
  cropCornerTR: {},
  cropCornerBL: {},
  cropCornerBR: {},
  cropBottomInfo: {
    padding: 16,
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
  },
  cropInstructionsText: {
    color: '#9CA3AF',
    fontSize: 14,
    textAlign: 'center',
  },
  cropBackgroundImage: {
    width: '100%',
    height: '100%',
  },
  cropOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  cropDarkArea: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  cropBox: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#C9A227',
    backgroundColor: 'transparent',
  },
  cropGridLine: {
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  cropGridLineHorizontal: {
    left: 0,
    right: 0,
    height: 1,
  },
  cropGridLineVertical: {
    top: 0,
    bottom: 0,
    width: 1,
  },
  cropHandle: {
    position: 'absolute',
    width: 24,
    height: 24,
    backgroundColor: '#C9A227',
    borderRadius: 12,
    borderWidth: 3,
    borderColor: '#fff',
  },
  cropHandleTopLeft: {},
  cropHandleTopRight: {},
  cropHandleBottomLeft: {},
  cropHandleBottomRight: {},
  cropBottomBar: {
    padding: 16,
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
  },
  cropInstructions: {
    color: '#9CA3AF',
    fontSize: 14,
  },
  // Legacy crop styles (keep for compatibility)
  cropPreviewContainer: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cropPreviewImage: {
    width: '100%',
    height: '100%',
    maxHeight: 300,
    borderRadius: 12,
  },
  cropControls: {
    padding: 20,
    backgroundColor: '#1A1A1A',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  cropControlsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 16,
  },
  cropSliderRow: {
    marginBottom: 16,
  },
  cropSliderLabel: {
    color: '#9CA3AF',
    fontSize: 14,
    marginBottom: 8,
  },
  cropSlider: {
    width: '100%',
    height: 40,
  },
  cropInfoRow: {
    alignItems: 'center',
    marginTop: 8,
  },
  cropInfoText: {
    color: '#6B7280',
    fontSize: 12,
  },
  // Mode Selection Styles
  modeSection: {
    marginTop: 12,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 12,
  },
  modeSectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 8,
  },
  modeToggle: {
    flexDirection: 'row',
    gap: 12,
  },
  modeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#C9A227',
    backgroundColor: 'transparent',
    gap: 8,
  },
  modeButtonActive: {
    backgroundColor: '#C9A227',
  },
  modeButtonText: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '600',
  },
  modeButtonTextActive: {
    color: '#fff',
  },
  // Color Selection Styles
  colorSection: {
    marginTop: 16,
  },
  colorSectionTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: '#9CA3AF',
    marginBottom: 10,
  },
  colorOptions: {
    flexDirection: 'row',
    gap: 10,
  },
  colorOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 2,
    backgroundColor: '#0F0F0F',
    gap: 6,
  },
  colorOptionActive: {
    backgroundColor: 'rgba(201, 162, 39, 0.15)',
  },
  colorDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  colorOptionText: {
    color: '#D1D5DB',
    fontSize: 12,
    fontWeight: '500',
  },
  // AI Button Styles
  aiButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#C9A227',
    paddingVertical: 16,
    borderRadius: 12,
    gap: 8,
  },
  aiButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  // Export buttons
  exportButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#2D2D2D',
  },
  exportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 6,
  },
  exportButtonText: {
    color: '#9CA3AF',
    fontSize: 13,
    fontWeight: '500',
  },
  // Revert to original button
  revertButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    paddingVertical: 8,
    gap: 6,
  },
  revertButtonIcon: {
    fontSize: 14,
  },
  revertButtonText: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: '500',
  },
  // Expand button
  expandButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  expandButtonText: {
    color: '#C9A227',
    fontSize: 12,
    fontWeight: '500',
  },
  // Updating overlay
  updatingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 8,
  },
  // Full-size preview modal
  previewModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  previewModalClose: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 10,
  },
  previewModalImage: {
    width: SCREEN_WIDTH - 40,
    height: SCREEN_HEIGHT * 0.5,
    borderRadius: 12,
  },
  previewModalActions: {
    flexDirection: 'row',
    marginTop: 20,
    gap: 30,
  },
  previewActionButton: {
    alignItems: 'center',
    gap: 6,
  },
  previewActionText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
  },
  // Zoom controls
  zoomControls: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 10,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  zoomButton: {
    padding: 8,
  },
  zoomText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    minWidth: 50,
    textAlign: 'center',
  },
  previewScrollView: {
    flex: 1,
    width: '100%',
  },
  previewScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewCompareHint: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(201, 162, 39, 0.2)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 10,
    gap: 8,
  },
  previewCompareText: {
    color: '#C9A227',
    fontSize: 13,
    fontWeight: '500',
  },
  // Preview compare button
  previewCompareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#C9A227',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 25,
    marginBottom: 15,
    gap: 8,
  },
  previewCompareButtonActive: {
    backgroundColor: '#C9A227',
  },
  previewCompareButtonText: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '600',
  },
  previewCompareButtonTextActive: {
    color: '#fff',
  },
  // Compare button for main view
  compareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#C9A227',
    paddingVertical: 10,
    borderRadius: 10,
    marginTop: 10,
    gap: 8,
  },
  compareButtonActive: {
    backgroundColor: '#C9A227',
  },
  compareButtonText: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '600',
  },
  compareButtonTextActive: {
    color: '#fff',
  },
  // Crop modal styles
  cropPreviewArea: {
    flex: 1,
    margin: 20,
    position: 'relative',
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    overflow: 'hidden',
  },
  cropIndicator: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#C9A227',
    backgroundColor: 'transparent',
  },
  cropSliders: {
    padding: 20,
    backgroundColor: '#1A1A1A',
  },
  cropImageArea: {
    flex: 1,
    margin: 20,
    position: 'relative',
  },
  // Welcome Screen Styles
  welcomeContainer: {
    flex: 1,
    backgroundColor: '#0A0A0A',
  },
  welcomeBackgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  welcomeOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  welcomeContentOverlay: {
    flex: 1,
    justifyContent: 'space-between',
  },
  welcomeTopSection: {
    paddingTop: 20,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  welcomeTaglineTop: {
    fontSize: 26,
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 36,
    fontWeight: '700',
    letterSpacing: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.9)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 10,
    textTransform: 'uppercase',
  },
  disclaimerUnderTagline: {
    marginTop: 16,
    paddingHorizontal: 10,
  },
  disclaimerTextLegible: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.75)',
    textAlign: 'center',
    lineHeight: 20,
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
  },
  welcomeMiddleSpacer: {
    flex: 1,
  },
  welcomeBottomButtonOnly: {
    alignItems: 'center',
    paddingBottom: 550,
  },
  welcomeBottomSimple: {
    alignItems: 'center',
    paddingBottom: 30,
  },
  welcomeBottomVersion: {
    alignItems: 'center',
    paddingBottom: 20,
  },
  welcomeButtonTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#C9A227',
    paddingVertical: 16,
    paddingHorizontal: 50,
    borderRadius: 30,
    gap: 10,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  welcomeTopSpacer: {
    flex: 0.15,
  },
  welcomeMainContent: {
    flex: 0.35,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  welcomeTitleNew: {
    fontSize: 42,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 6,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 8,
  },
  welcomeSubtitleNew: {
    fontSize: 14,
    fontWeight: '600',
    color: '#C9A227',
    letterSpacing: 4,
    marginTop: 8,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
  },
  welcomeTaglineNew: {
    fontSize: 18,
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 28,
    marginTop: 24,
    fontStyle: 'italic',
    fontWeight: '300',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 6,
  },
  welcomeBottomSection: {
    flex: 0.5,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingBottom: 30,
  },
  welcomeBottomSectionNew: {
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  welcomeButtonNew: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#C9A227',
    paddingVertical: 18,
    paddingHorizontal: 60,
    borderRadius: 35,
    gap: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  welcomeButtonTextNew: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0A0A0A',
    letterSpacing: 1,
  },
  welcomeButtonArrowNew: {
    fontSize: 20,
    color: '#0A0A0A',
    fontWeight: '400',
  },
  disclaimerContainerNew: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 10,
    borderWidth: 1,
    borderColor: 'rgba(201, 162, 39, 0.3)',
    backdropFilter: 'blur(10px)',
  },
  disclaimerContainerWide: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginBottom: 12,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(201, 162, 39, 0.25)',
  },
  disclaimerTextWide: {
    fontSize: 10,
    color: '#AAAAAA',
    lineHeight: 16,
    textAlign: 'center',
  },
  disclaimerTitleNew: {
    fontSize: 11,
    fontWeight: '700',
    color: '#C9A227',
    textAlign: 'center',
    marginBottom: 10,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  disclaimerTextNew: {
    fontSize: 11,
    color: '#CCCCCC',
    lineHeight: 18,
    textAlign: 'left',
  },
  welcomeVersionNew: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.5)',
    textAlign: 'center',
    fontFamily: 'monospace',
  },
  welcomeContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingBottom: 40,
  },
  welcomeLogo: {
    width: 120,
    height: 120,
    borderRadius: 20,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: '#C9A227',
  },
  welcomeTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#C9A227',
    letterSpacing: 3,
    textAlign: 'center',
  },
  welcomeSubtitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8B7355',
    letterSpacing: 2,
    marginTop: 4,
    marginBottom: 30,
    textTransform: 'uppercase',
  },
  welcomeTagline: {
    fontSize: 15,
    color: '#A89060',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 40,
    paddingHorizontal: 10,
    fontStyle: 'italic',
  },
  welcomeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#C9A227',
    paddingVertical: 16,
    paddingHorizontal: 50,
    borderRadius: 30,
    gap: 10,
    marginBottom: 30,
  },
  welcomeButtonText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0A0A0A',
    letterSpacing: 1,
  },
  welcomeButtonArrow: {
    fontSize: 18,
    color: '#0A0A0A',
    fontWeight: '300',
  },
  welcomeFooter: {
    fontSize: 11,
    color: '#6B5D48',
    textAlign: 'center',
    fontStyle: 'italic',
    letterSpacing: 0.5,
  },
  welcomeVersion: {
    fontSize: 10,
    color: '#4A4A4A',
    textAlign: 'center',
    marginTop: 12,
    fontFamily: 'monospace',
  },
  disclaimerContainer: {
    backgroundColor: 'rgba(201, 162, 39, 0.08)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    marginHorizontal: 10,
    borderWidth: 1,
    borderColor: 'rgba(201, 162, 39, 0.2)',
  },
  disclaimerTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#C9A227',
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  disclaimerText: {
    fontSize: 11,
    color: '#8B7355',
    lineHeight: 18,
    textAlign: 'left',
  },
  // Photo Library Grid Styles
  photoLibraryContainer: {
    flex: 1,
    minHeight: 400,
  },
  photoLibraryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  photoLibraryTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#C9A227',
  },
  cameraButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1510',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#C9A227',
    gap: 6,
  },
  cameraButtonIcon: {
    fontSize: 16,
  },
  cameraButtonText: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '600',
  },
  loadingPhotosContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 300,
  },
  loadingPhotosText: {
    color: '#9CA3AF',
    marginTop: 12,
    fontSize: 14,
  },
  noPhotosContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 300,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
  },
  noPhotosIcon: {
    fontSize: 40,
    marginBottom: 12,
  },
  noPhotosText: {
    color: '#9CA3AF',
    fontSize: 16,
    marginBottom: 20,
  },
  grantAccessButton: {
    backgroundColor: '#C9A227',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
  },
  grantAccessButtonText: {
    color: '#0A0A0A',
    fontSize: 14,
    fontWeight: '600',
  },
  photoGrid: {
    flex: 1,
  },
  photoGridInner: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  photoGridItem: {
    width: (SCREEN_WIDTH - 40 - 8) / 3,
    aspectRatio: 1,
    borderRadius: 4,
    overflow: 'hidden',
  },
  photoGridImage: {
    width: '100%',
    height: '100%',
  },
  loadMoreButton: {
    alignItems: 'center',
    paddingVertical: 16,
    marginTop: 8,
  },
  loadMoreText: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '500',
  },
  // Minimal Share Row Styles (compact)
  minimalShareRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    gap: 8,
  },
  minimalShareButton: {
    padding: 8,
  },
  minimalShareIcon: {
    fontSize: 18,
  },
  minimalShareDivider: {
    color: '#444',
    fontSize: 14,
  },
  minimalShareText: {
    color: '#666',
    fontSize: 12,
    marginLeft: 4,
  },
  // Share & Review Section Styles (legacy - keeping for reference)
  shareReviewSection: {
    marginTop: 30,
    backgroundColor: '#1A1510',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(201, 162, 39, 0.3)',
  },
  shareReviewTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#C9A227',
    marginBottom: 6,
    textAlign: 'center',
  },
  shareReviewSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 16,
    textAlign: 'center',
  },
  shareReviewButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  reviewButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#C9A227',
    paddingVertical: 12,
    borderRadius: 25,
    gap: 6,
  },
  reviewButtonIcon: {
    fontSize: 16,
  },
  reviewButtonText: {
    color: '#0A0A0A',
    fontSize: 14,
    fontWeight: '600',
  },
  shareAppButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#C9A227',
    paddingVertical: 12,
    borderRadius: 25,
    gap: 6,
  },
  shareAppButtonIcon: {
    fontSize: 16,
  },
  shareAppButtonText: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '600',
  },
  
  // ========== EDIT MODE STYLES ==========
  editModalContainer: {
    flex: 1,
    backgroundColor: '#0A0A0A',
  },
  editModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 50,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#C9A227',
    backgroundColor: '#0D0D0D',
  },
  editModalCloseText: {
    color: '#9CA3AF',
    fontSize: 16,
    fontWeight: '500',
  },
  editModalTitle: {
    color: '#C9A227',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 1,
  },
  editModalSaveText: {
    color: '#C9A227',
    fontSize: 16,
    fontWeight: '700',
  },
  editCanvasContainer: {
    flex: 1,
    backgroundColor: '#1A1A1A',
    position: 'relative',
    overflow: 'hidden',
  },
  editCanvasInner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  zoomIndicator: {
    position: 'absolute',
    top: 60,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    zIndex: 100,
    gap: 8,
  },
  zoomIndicatorText: {
    color: '#C9A227',
    fontSize: 14,
    fontWeight: '600',
  },
  resetZoomButton: {
    backgroundColor: '#C9A227',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  resetZoomText: {
    color: '#0A0A0A',
    fontSize: 12,
    fontWeight: '600',
  },
  editHintWrapper: {
    position: 'absolute',
    top: 70,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 100,
  },
  editHintContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#C9A227',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  editHintText: {
    color: '#C9A227',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  editBackgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  editStencilOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  editDrawingLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  editControlsContainer: {
    backgroundColor: '#0D0D0D',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#333',
  },
  editSliderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  editSliderLabel: {
    color: '#E5E5E5',
    fontSize: 13,
    fontWeight: '500',
    width: 100,
  },
  editSlider: {
    flex: 1,
    height: 40,
  },
  editSliderValue: {
    color: '#C9A227',
    fontSize: 13,
    fontWeight: '600',
    width: 45,
    textAlign: 'right',
  },
  // Mode Toggle - Draw vs Navigate
  modeToggleRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 12,
    gap: 12,
  },
  modeToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
    backgroundColor: '#1A1A1A',
    borderWidth: 2,
    borderColor: '#333',
    gap: 8,
  },
  modeToggleActive: {
    backgroundColor: '#C9A227',
    borderColor: '#C9A227',
  },
  modeToggleIcon: {
    fontSize: 16,
  },
  modeToggleText: {
    color: '#9CA3AF',
    fontSize: 14,
    fontWeight: '600',
  },
  modeToggleTextActive: {
    color: '#0A0A0A',
  },
  resetZoomInlineButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 25,
    backgroundColor: '#8B7355',
    gap: 6,
  },
  resetZoomInlineText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  editSaveToGalleryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#C9A227',
    paddingVertical: 14,
    borderRadius: 25,
    gap: 8,
  },
  editSaveToGalleryIcon: {
    fontSize: 18,
  },
  editSaveToGalleryText: {
    color: '#0A0A0A',
    fontSize: 16,
    fontWeight: '700',
  },
  // Procreate-Style Full Screen Editor
  procreateContainer: {
    flex: 1,
    backgroundColor: '#1A1A1A',
  },
  procreateCanvas: {
    flex: 1,
    backgroundColor: '#2A2A2A',
  },
  procreateCanvasInner: {
    flex: 1,
    position: 'relative',
  },
  procreateBackgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  procreateStencilImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  procreateDrawingLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  procreateLeftBar: {
    position: 'absolute',
    left: 12,
    top: '15%',
    bottom: '25%',
    width: 50,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 30,
  },
  procreateBrushSliderContainer: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 8,
    width: 50,
    height: 180,
  },
  procreateBrushLabel: {
    color: '#888',
    fontSize: 9,
    fontWeight: '600',
    marginBottom: 8,
  },
  procreateBrushSliderWrapper: {
    flex: 1,
    width: 150,
    justifyContent: 'center',
    alignItems: 'center',
  },
  procreateBrushSlider: {
    width: '100%',
    height: 40,
  },
  procreateBrushValue: {
    color: '#C9A227',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 8,
  },
  procreateTopBar: {
    position: 'absolute',
    top: 50,
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  procreateTopButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 20,
  },
  procreateTopButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  procreateTopButtonDone: {
    backgroundColor: '#C9A227',
  },
  procreateTopButtonTextDone: {
    color: '#0A0A0A',
    fontSize: 16,
    fontWeight: '700',
  },
  procreateRightBar: {
    position: 'absolute',
    right: 12,
    top: '30%',
    gap: 12,
  },
  procreateToolButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  procreateToolActive: {
    backgroundColor: '#C9A227',
  },
  procreateToolIcon: {
    fontSize: 22,
  },
  procreateBottomBar: {
    position: 'absolute',
    bottom: 40,
    left: 16,
    right: 16,
    alignItems: 'center',
  },
  procreateSaveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#C9A227',
    gap: 10,
  },
  procreateSaveIcon: {
    fontSize: 18,
  },
  procreateSaveText: {
    color: '#C9A227',
    fontSize: 15,
    fontWeight: '600',
  },
  procreateDrawModeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#666',
    gap: 8,
  },
  procreateDrawModeButtonActive: {
    borderColor: '#4CAF50',
    backgroundColor: 'rgba(76, 175, 80, 0.2)',
  },
  procreateDrawModeIcon: {
    fontSize: 18,
  },
  procreateDrawModeText: {
    color: '#999',
    fontSize: 14,
    fontWeight: '700',
  },
  procreateDrawModeTextActive: {
    color: '#4CAF50',
  },
  procreateHint: {
    position: 'absolute',
    top: 110,
    left: 16,
    right: 16,
    alignItems: 'center',
  },
  procreateHintText: {
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    color: '#C9A227',
    fontSize: 11,
    fontWeight: '600',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 15,
    overflow: 'hidden',
    textAlign: 'center',
  },
  procreateTopHintBar: {
    position: 'absolute',
    top: 100,
    left: 16,
    right: 16,
    alignItems: 'center',
    gap: 10,
  },
  modeToggleContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    borderRadius: 25,
    padding: 4,
    gap: 4,
  },
  modeToggleBtn: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  modeToggleBtnActive: {
    backgroundColor: '#C9A227',
  },
  modeToggleBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  // Onboarding Tutorial Styles
  onboardingOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  onboardingCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 24,
    padding: 32,
    maxWidth: 400,
    width: '100%',
    borderWidth: 2,
    borderColor: '#C9A227',
    shadowColor: '#C9A227',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  onboardingContent: {
    alignItems: 'center',
    marginBottom: 24,
  },
  onboardingIcon: {
    fontSize: 64,
    marginBottom: 16,
  },
  onboardingTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#C9A227',
    textAlign: 'center',
    marginBottom: 8,
  },
  onboardingSubtitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#999',
    textAlign: 'center',
    marginBottom: 16,
  },
  onboardingDescription: {
    fontSize: 15,
    color: '#CCCCCC',
    textAlign: 'center',
    lineHeight: 24,
  },
  onboardingDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 24,
    gap: 8,
  },
  onboardingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#333',
  },
  onboardingDotActive: {
    backgroundColor: '#C9A227',
    width: 24,
  },
  onboardingButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
    marginBottom: 16,
  },
  onboardingBackButton: {
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#666',
  },
  onboardingBackText: {
    color: '#999',
    fontSize: 16,
    fontWeight: '600',
  },
  onboardingNextButton: {
    backgroundColor: '#C9A227',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 25,
  },
  onboardingNextText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '700',
  },
  onboardingSkip: {
    alignItems: 'center',
  },
  onboardingSkipText: {
    color: '#666',
    fontSize: 14,
    textDecorationLine: 'underline',
  },
  // PSD Export Loading Overlay
  exportLoadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  exportLoadingCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#C9A227',
    shadowColor: '#C9A227',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  exportLoadingTitle: {
    color: '#C9A227',
    fontSize: 18,
    fontWeight: '600',
    marginTop: 16,
    marginBottom: 8,
  },
  exportLoadingText: {
    color: '#888',
    fontSize: 14,
    textAlign: 'center',
  },
  // Credits header badge
  creditsHeaderBadge: {
    backgroundColor: 'rgba(201,162,39,0.15)',
    borderWidth: 1,
    borderColor: '#C9A227',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignItems: 'center',
    marginRight: 4,
  },
  creditsHeaderText: {
    color: '#C9A227',
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 18,
  },
  creditsHeaderLabel: {
    color: '#C9A227',
    fontSize: 8,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
});
